//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sebastian_soteno.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sebastian_sotenoEntities1 : DbContext
    {
        public sebastian_sotenoEntities1()
            : base("name=sebastian_sotenoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Presentaciones> Cat_Presentaciones { get; set; }
        public virtual DbSet<Cat_Productos> Cat_Productos { get; set; }
    
        public virtual ObjectResult<spProducto_Result> spProducto(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, string nombre)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spProducto_Result>("spProducto", fechaInicialParameter, fechaFinalParameter, nombreParameter);
        }
    }
}
